
// used for sending the generated mail here for reset password link
const nodeMailer = require('nodemailer')

const SendResetEmail = async(UserParameterWithMessage)=>{


    console.log("sending email for reset")

    const SMPT_MAIL = "TestMernProject@gmail.com";
    const SMPT_PASSWORD="ShefaliVerma" //here we will use other password generated by GOOGLE on allowing access of third-party software for mailing. here i have password as: "ecucxsolicfkzyqj"
    
    const SMPT_Google_secure_Password = "ecucxsolicfkzyqj";


    const transporter = nodeMailer.createTransport({
        
        host:"smpt.gmail.com",//This line is used if Transported function gives error of Bad Credentials
        port:465, // This line is also added for the same above erre of Invalid Login.. This error generally happens with GMAIL Accounts


        service:"gmail",
        auth:{
            user:SMPT_MAIL,
            pass:SMPT_Google_secure_Password,
        }
    })

    console.log("transported email for reset")

    const mailOptions = {
        from:SMPT_MAIL,
        to:UserParameterWithMessage.email,
        subject:UserParameterWithMessage.subject,
        text:UserParameterWithMessage.message
    }

    await transporter.sendMail(mailOptions);

    console.log("gaya mail from nodemailer")

}


module.exports = SendResetEmail;